export const NIFTY_100 = [
  "ABB", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", 
  "AMBUJACEM", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", 
  "BAJAJFINSV", "BAJFINANCE", "BANKBARODA", "BEL", "BHARTIARTL", 
  "BPCL", "BRITANNIA", "CIPLA", "COALINDIA", "DLF", "DMART", 
  "DRREDDY", "EICHERMOT", "GAIL", "GODREJCP", "GRASIM", "HAL", 
  "HCLTECH", "HDFCBANK", "HDFCLIFE", "HINDALCO", "HINDUNILVR", 
  "ICICIBANK", "INDIGO", "INDUSINDBK", "INFY", "ITC", 
  "JSWSTEEL", "KOTAKBANK", "LT", "LTIM", "M&M", "MARUTI", 
  "NESTLEIND", "NTPC", "ONGC", "POWERGRID", "RELIANCE", 
  "SBILIFE", "SBIN", "SUNPHARMA", "TATACONSUM", "TATAMOTORS", 
  "TATAPOWER", "TATASTEEL", "TCS", "TECHM", "TITAN", 
  "ULTRACEMCO", "WIPRO", "ZOMATO"
];