export const NIFTY_DIRECTORY = [
  { symbol: 'ABB', name: 'ABB India Ltd', website: 'https://new.abb.com/in' },
  { symbol: 'ADANIENSOL', name: 'Adani Energy Solutions Ltd', website: 'https://www.adanienergysolutions.com' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd', website: 'https://www.adanienterprises.com' },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy Ltd', website: 'https://www.adanigreenenergy.com' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & Special Economic Zone Ltd', website: 'https://www.adaniports.com' },
  { symbol: 'ADANIPOWER', name: 'Adani Power Ltd', website: 'https://www.adanipower.com' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements Ltd', website: 'https://www.ambujacement.com' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd', website: 'https://www.apollohospitals.com' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd', website: 'https://www.asianpaints.com' },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd', website: 'https://www.axisbank.com' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd', website: 'https://www.bajajauto.com' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd', website: 'https://www.bajajfinserv.in' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd', website: 'https://www.bajajfinserv.in/bajaj-finance' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', website: 'https://www.bankofbaroda.in' },
  { symbol: 'BEL', name: 'Bharat Electronics Ltd', website: 'https://bel-india.in' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd', website: 'https://www.airtel.in' },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corporation Ltd', website: 'https://www.bharatpetroleum.in' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd', website: 'https://www.britannia.co.in' },
  { symbol: 'CIPLA', name: 'Cipla Ltd', website: 'https://www.cipla.com' },
  { symbol: 'COALINDIA', name: 'Coal India Ltd', website: 'https://www.coalindia.in' },
  { symbol: 'DLF', name: 'DLF Ltd', website: 'https://www.dlf.in' },
  { symbol: 'DMART', name: 'Avenue Supermarts Ltd', website: 'https://www.dmart.in' },
  { symbol: 'DRREDDY', name: "Dr. Reddy's Laboratories Ltd", website: 'https://www.drreddys.com' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd', website: 'https://www.eicher.in' },
  { symbol: 'GAIL', name: 'GAIL (India) Ltd', website: 'https://gailonline.com' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products Ltd', website: 'https://www.godrejcp.com' },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd', website: 'https://www.grasim.com' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics Ltd', website: 'https://hal-india.co.in' },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd', website: 'https://www.hcltech.com' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd', website: 'https://www.hdfcbank.com' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance Company Ltd', website: 'https://www.hdfclife.com' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd', website: 'https://www.hindalco.com' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd', website: 'https://www.hul.co.in' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd', website: 'https://www.icicibank.com' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation Ltd', website: 'https://www.goindigo.in' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd', website: 'https://www.indusind.com' },
  { symbol: 'INFY', name: 'Infosys Ltd', website: 'https://www.infosys.com' },
  { symbol: 'ITC', name: 'ITC Ltd', website: 'https://www.itcportal.com' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd', website: 'https://www.jswsteel.in' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd', website: 'https://www.kotak.com' },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd', website: 'https://www.larsentoubro.com' },
  { symbol: 'LTIM', name: 'LTIMindtree Ltd', website: 'https://www.ltimindtree.com' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra Ltd', website: 'https://www.mahindra.com' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd', website: 'https://www.marutisuzuki.com' },
  { symbol: 'NESTLEIND', name: 'Nestlé India Ltd', website: 'https://www.nestle.in' },
  { symbol: 'NTPC', name: 'NTPC Ltd', website: 'https://www.ntpc.co.in' },
  { symbol: 'ONGC', name: 'Oil and Natural Gas Corporation Ltd', website: 'https://www.ongcindia.com' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India Ltd', website: 'https://www.powergridindia.com' },
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd', website: 'https://www.ril.com' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance Company Ltd', website: 'https://www.sbilife.co.in' },
  { symbol: 'SBIN', name: 'State Bank of India', website: 'https://www.sbi.co.in' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd', website: 'https://www.sunpharma.com' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products Ltd', website: 'https://www.tataconsumer.com' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd', website: 'https://www.tatamotors.com' },
  { symbol: 'TATAPOWER', name: 'Tata Power Company Ltd', website: 'https://www.tatapower.com' },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd', website: 'https://www.tatasteel.com' },
  { symbol: 'TCS', name: 'Tata Consultancy Services Ltd', website: 'https://www.tcs.com' },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd', website: 'https://www.techmahindra.com' },
  { symbol: 'TITAN', name: 'Titan Company Ltd', website: 'https://www.titancompany.in' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd', website: 'https://www.ultratechcement.com' },
  { symbol: 'WIPRO', name: 'Wipro Ltd', website: 'https://www.wipro.com' },
  { symbol: 'ZOMATO', name: 'Zomato Ltd', website: 'https://www.zomato.com' }
];
